"use client";

import { useCallback, useEffect, useState } from "react";

// Set when the user asks for the waiting update. The first install also
// changes the controller (clients.claim), and that must not reload the page
// under someone who just arrived.
let updateRequested = false;

/**
 * Register the service worker (production builds only; it's generated by
 * scripts/build-sw.mjs) and report when a new version is waiting.
 * `applyUpdate` activates it and reloads once it has taken control.
 */
export function useServiceWorker(): { updateReady: boolean; applyUpdate: () => void } {
  const [waiting, setWaiting] = useState<ServiceWorker | null>(null);

  useEffect(() => {
    if (process.env.NODE_ENV !== "production" || !("serviceWorker" in navigator)) return;
    let cancelled = false;
    let onVisible: (() => void) | null = null;

    const watch = (registration: ServiceWorkerRegistration) => {
      // A worker already waiting from an earlier visit.
      if (registration.waiting && navigator.serviceWorker.controller) setWaiting(registration.waiting);
      registration.addEventListener("updatefound", () => {
        const incoming = registration.installing;
        incoming?.addEventListener("statechange", () => {
          // "installed" with a controller = an update, not the first install.
          if (!cancelled && incoming.state === "installed" && navigator.serviceWorker.controller) {
            setWaiting(incoming);
          }
        });
      });
    };

    navigator.serviceWorker
      .register("/sw.js")
      .then((registration) => {
        if (cancelled) return;
        watch(registration);
        // Check for a new deploy when the app comes back to the foreground.
        onVisible = () => {
          if (document.visibilityState === "visible") void registration.update().catch(() => undefined);
        };
        document.addEventListener("visibilitychange", onVisible);
      })
      .catch(() => {
        // No offline support this visit (e.g. private mode); the app still works.
      });

    let reloading = false;
    const onControllerChange = () => {
      if (!updateRequested || reloading) return;
      reloading = true;
      window.location.reload();
    };
    navigator.serviceWorker.addEventListener("controllerchange", onControllerChange);
    return () => {
      cancelled = true;
      navigator.serviceWorker.removeEventListener("controllerchange", onControllerChange);
      if (onVisible) document.removeEventListener("visibilitychange", onVisible);
    };
  }, []);

  const applyUpdate = useCallback(() => {
    updateRequested = true;
    waiting?.postMessage({ type: "SKIP_WAITING" });
  }, [waiting]);

  return { updateReady: waiting !== null, applyUpdate };
}
